[build]
  command = "bash ./scripts/netlify-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

# Variables de entorno para las funciones
[template.environment]
  SUPABASE_URL = "URL de tu proyecto Supabase"
  SUPABASE_SERVICE_ROLE_KEY = "Service Role Key de Supabase"

# Configuración para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 