[build]
  command = "bash ./scripts/netlify-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuración para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 